export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const INSERT_EMPLOYEE = 'INSERT_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const GET_USERS_MESSAGES = 'GET_USERS_MESSAGES';

export const GET_MESSAGES = 'GET_MESSAGES';
export const INSERT_MESSAGE = 'INSERT_MESSAGE';

export const GET_JOBS = 'GET_JOBS';
export const INSERT_JOB = 'INSERT_JOB';
export const UPDATE_JOB = 'UPDATE_JOB';
export const DELETE_JOB = 'DELETE_JOB';

export const GET_SWITCHERS = 'GET_SWITCHERS';
export const INSERT_SWITCHER = 'INSERT_SWITCHER';
export const UPDATE_SWITCHER = 'UPDATE_SWITCHER';
export const DELETE_SWITCHER = 'DELETE_SWITCHER';

export const GET_STUDIOS = 'GET_STUDIOS';
export const INSERT_STUDIO = 'INSERT_STUDIO';
export const UPDATE_STUDIO = 'UPDATE_STUDIO';
export const DELETE_STUDIO = 'DELETE_STUDIO';

export const GET_TVSHOWS = 'GET_TVSHOWS';
export const INSERT_TVSHOW = 'INSERT_TVSHOW';
export const UPDATE_TVSHOW = 'UPDATE_TVSHOW';
export const DELETE_TVSHOW = 'DELETE_TVSHOW';

export const GET_EMPLOYEES_TIMES = 'GET_EMPLOYEES_TIMES';
export const INSERT_EMPLOYEE_TIME = 'INSERT_EMPLOYEE_TIME';
export const UPDATE_EMPLOYEE_TIME = 'UPDATE_EMPLOYEE_TIME';
export const DELETE_EMPLOYEE_TIME = 'DELETE_EMPLOYEE_TIME';

export const GET_TV_SHOW_TIMES = 'GET_TV_SHOW_TIMES';
export const INSERT_TV_SHOW_TIME = 'INSERT_TV_SHOW_TIME';
export const UPDATE_TV_SHOW_TIME = 'UPDATE_TV_SHOW_TIME';
export const DELETE_TV_SHOW_TIME = 'DELETE_TV_SHOW_TIME';

export const SEND_MAIL = 'SEND_MAIL';
export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
