export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';

export const DEFINE_EMPLOYEES = 'DEFINE_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';

export const DEFINE_MESSAGES= 'DEFINE_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const DEFINE_JOBS = 'DEFINE_JOBS';
export const ADD_JOB = 'ADD_JOB';
export const CHANGE_JOB = 'CHANGE_JOB';
export const REMOVE_JOB = 'REMOVE_JOB';

export const DEFINE_SWITCHERS = 'DEFINE_SWITCHERS';
export const ADD_SWITCHER = 'ADD_SWITCHER';
export const CHANGE_SWITCHER = 'CHANGE_SWITCHER';
export const REMOVE_SWITCHER = 'REMOVE_SWITCHER';

export const DEFINE_STUDIOS = 'DEFINE_STUDIOS';
export const ADD_STUDIO = 'ADD_STUDIO';
export const CHANGE_STUDIO = 'CHANGE_STUDIO';
export const REMOVE_STUDIO = 'REMOVE_STUDIO';

export const DEFINE_TVSHOWS = 'DEFINE_TVSHOWS';
export const ADD_TVSHOW = 'ADD_TVSHOW';
export const CHANGE_TVSHOW = 'CHANGE_TVSHOW';
export const REMOVE_TVSHOW = 'REMOVE_TVSHOW';

export const DEFINE_EMPLOYEES_TIMES = 'DEFINE_EMPLOYEES_TIMES';
export const ADD_EMPLOYEE_TIME = 'ADD_EMPLOYEE_TIME';
export const CHANGE_EMPLOYEE_TIME = 'CHANGE_EMPLOYEE_TIME';
export const REMOVE_EMPLOYEE_TIME = 'REMOVE_EMPLOYEE_TIME';
export const ADD_OR_CHANGE_EMPLOYEE_TIME = 'ADD_OR_CHANGE_EMPLOYEE_TIME';

export const DEFINE_TV_SHOW_TIMES = 'DEFINE_TV_SHOW_TIMES';
export const ADD_TV_SHOW_TIME = 'ADD_TV_SHOW_TIME';
export const CHANGE_TV_SHOW_TIME = 'CHANGE_TV_SHOW_TIME';
export const REMOVE_TV_SHOW_TIME = 'REMOVE_TV_SHOW_TIME';
export const ADD_OR_CHANGE_TV_SHOW_TIME = 'ADD_OR_CHANGE_TV_SHOW_TIME';
