<?php $this->start('error') ?>
	<div class="alert alert-danger"><?= "Ops, {$error}." ?></div>
<?php $this->stop() ?>

<!DOCTYPE html>
<html>

<head>
	<title>Business Schedule</title>
	<link rel="stylesheet" type="text/css" href="/assets/css/error.css">
	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<main>
		<img class="wave" src="/assets/images/wave.png">
		<div class="container">

			<h2>Oops! Página não encontrada.</h2>

			<h1>404</h1>

			<p>Não podemos encontrar a página que você está procurando.</p>

			<a href="/home">Volte a página inicial</a>

		</div>
	</main>
</body>
</html>