<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?=  "Business Schedule - {$title}" ?></title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/animate.min.css">
    <link rel="stylesheet" href="/assets/css/light-bootstrap-dashboard.css">
    <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
	<!-- <script src="https://kit.fontawesome.com/a81368914c.js"></script> -->
    <!-- <link rel="stylesheet" type="text/css" href="./assets/css/<?= $file ?>.css"> -->
</head>
<body>

    <div class="wrapper">
        <side class="sidebar" data-color="blue" data-image="/assets/images/sidebar-4.jpg">
            <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="/" class="simple-text">
                        Business Schedule
                    </a>
                </div>
                <ul class="nav">
                    <li><a href="#"><i class="fa fa-map-marker"></i> Cadastrar Escala</a></li>
                    <li><a href="#"><i class="fa fa-industry fa-sm"></i> Editar Escala</a></li>
                    <li><a href="#"><i class="fa fa-cubes fa-sm"></i> Cadastrar Funcionário</a></li>
                    <li><a href="#"><i class="fa fa-users"></i> Editar Funcionário</a></li>
                    <li><a href="#"><i class="fa fa-shopping-cart"></i> Consultar Funcionário</a></li>
                    <li><a href="#"><i class="fa fa-file-text-o"></i> Consultar Escala</a></li>
                    <li><a href="#"><i class="fa fa-file-text-o"></i> Solicitar Troca de Horário</a></li>
                    <li>
                </ul>
            </div>
        </side>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-light navbar-expand-lg navbar-fixed">
                <header class="container-fluid flex-nowrap">
                    <div class="navbar-header mx-0">
                        <a class="navbar-brand py-0" href="index.php?class=ViewSource&method=onView&source={class}"> <i class="fa fa-code"></i> Código-fonte</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="nav navbar-nav">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-dashboard"></i>
                                    <p class="d-lg-none d-md-none">Dashboard</p>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Ação</a>
                                    <a class="dropdown-item" href="#">Outra ação</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Algo mais aqui</a>
                                </div>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav ml-auto align-items-center">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <p class="d-inline-block">
                                        Atalhos
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="index.php?class=ProdutosList">Escalas</a></li>
                                    <li><a href="index.php?class=PessoasList">Funcionários</a></li>
                                    <li><a href="index.php?class=VendasForm">Programas</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="index.php?class=LoginForm&method=onLogout" class="my-0">
                                    <p>Sair</p>
                                </a>
                            </li>
                            <li class="separator d-lg-none d-md-none"></li>
                        </ul>
                    </div>
                </header>
            </nav>
            <main class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">

                            <?= $this->section('content') ?>

                        </div>
                    </div>
                </div>
            </main>
            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        <a target="newwindow" href="http://app-controle-vendas.rf.gd"> PHP - Programando com Orientação a Objetos </a>
                    </p>
                </div>
            </footer>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"	integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"	crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="/assets/js/Chart.bundle.min.js"></script>
    <script src="/assets/js/light-bootstrap-dashboard.js"></script>
    <script type="text/javascript" src="./assets/js/<?= $file ?>.js"></script>
    <script src="/assets/js/script.js"></script>

</body>
</html>