<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?></title>
    <link rel="shortcut icon" href="/assets/images/TV_Aparecida_2010.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/animate.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/assets/css/light-bootstrap-dashboard.css">
    <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <!-- <script src="https://kit.fontawesome.com/a81368914c.js"></script> -->
    <link rel="stylesheet" type="text/css" href="/assets/css/<?= $file ?>.css">
</head>

<body>

    <div class="wrapper">
        <side class="sidebar" data-color="blue" data-image="/assets/images/sidebar-4.jpg" id="navigation-example-2">
            <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="/" class="simple-text">
                        Business Schedule
                    </a>
                </div>
                <?php if (session()->__get('level') == 2) : ?>
                    <ul class="nav flex-column">
                        <li class="nav-item"><a class="nav-link" href="/escala"><i class="fa fa-calendar" aria-hidden="true"></i> Cadastrar Escala</a></li>
                        <li class="nav-item"><a class="nav-link" href="#"><i class="fa fa-industry fa-sm" aria-hidden="true"></i> Editar Escala</a></li>
                        <li class="nav-item"><a class="nav-link" href="/funcionario"><i class="fa fa-users" aria-hidden="true"></i> Funcionários</a></li>
                        <li class="nav-item"><a class="nav-link" href="/estudio"><i class="fa fa-video-camera" aria-hidden="true"></i> Estúdios</a></li>
                        <li class="nav-item"><a class="nav-link" href="/switcher"><i class="fa fa-film" aria-hidden="true"></i> Switchers</a></li>
                        <li class="nav-item"><a class="nav-link" href="/programa"><i class="fa fa-television" aria-hidden="true"></i> Programas</a></li>
                        <li class="nav-item"><a class="nav-link" href="/horario-programa"><i class="fa fa-clock-o" aria-hidden="true"></i> Horários de Programas</a></li>
                        <li class="nav-item"><a class="nav-link" href="/admin"><i class="fa fa-user" aria-hidden="true"></i> Administradores</a></li>
                    </ul>
                <?php else: ?>
                    <ul class="nav flex-column">
                        <li class="nav-item"><a class="nav-link" href="/escala"><i class="fa fa-calendar" aria-hidden="true"></i> Visualizar escala</a></li>
                        <li class="nav-item"><a class="nav-link" href="#"><i class="fa fa-file-text-o" aria-hidden="true"></i> Solicitar Troca de Horário</a></li>
                    </ul>
                <?php endif ?>
                
            </div>
        </side>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-light navbar-expand-lg navbar-fixed color-nav">
                <header class="container-fluid flex-nowrap">
                    <div class="navbar-header mx-0">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation-example-2" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                    </div>
                    <div class="collapse navbar-collapse mb-nav">
                        <ul class="nav navbar-nav ml-lg-auto align-items-lg-center">
                            <img src="/assets/images/TV_Aparecida_2010.png" width="20" height="20" class="rounded-circle ml-2">
                            <li>
                                <a href="/sair" class="my-0">
                                    <p>Sair</p>
                                </a>
                            </li>
                            <li class="separator d-lg-none d-md-none"></li>
                        </ul>
                    </div>
                </header>
            </nav>
            <main class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">

                            <?= $this->section('content') ?>

                        </div>
                    </div>
                </div>
            </main>
            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        <a target="newwindow" href="https://github.com/andr3m0ur4/Business-Schedule"> PI - Programando com Orientação a Objetos </a>
                    </p>
                </div>
            </footer>
        </div>
    </div>

    <div id="myModal"></div>

    <script src="/assets/js/Chart.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="/assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>
    <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/sortablejs) -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <script src="/assets/js/localStorage.js"></script>
    <script type="text/javascript" src="/assets/js/<?= $file ?>.js"></script>
    <script src="/assets/js/script.js"></script>
</body>

</html>