<?php $this->layout('_template', $this->data) ?>

<div class="alert alert-warning question d-none" id="question">
    Deseja realmente excluir o registro?
    <a href="#" class="btn btn-light float-right">Sim</a>
</div>

<?php if (isset($message)) : ?>
    <div class="alert alert-info">
        Registro excluído com sucesso
        <button type="button" aria-label="Close" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif ?>

<section>
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Administrador</h4>
            </div>
        </div>

        <div class="card-body">
            <form name="form_admin" method="get">
                <div class="form-row align-items-center text-right">
                    <label for="name" class="col-sm-2 col-form-label">Nome</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                </div>
            </form>
        </div>

        <div class="card-footer">
            <div>
                <button name="search" type="button" class="btn btn-success">Buscar</button>
                <button name="new" type="button" class="btn btn-secondary">Novo</button>
            </div>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-body">

            <table class="table table-striped table-hover table-responsive">
                <thead>
                    <tr>
                        <th>
                        <th>
                        <th class="text-center" width="10%">Código</th>
                        <th class="text-left" width="40%">Nome</th>
                        <th class="text-left" width="40%">Email</th>
                        <th class="text-right" width="15%">Telefone</th>
                    </tr>
                </thead>
                <tbody>

                    <?php foreach ($administrators as $administrator) : ?>
                        <tr>
                            <td class="text-center">
                                <a href="/admin/<?= $administrator->getId() ?>/perfil">
                                    <i class="fa fa-edit fa-lg blue" title="Editar"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="#" data-id="<?= $administrator->getId() ?>">
                                    <i class="fa fa-trash fa-lg red" title="Excluir"></i>
                                </a>
                            </td>
                            <td class="text-center" width="10%"><?= $administrator->getId() ?></td>
                            <td class="text-left" width="40%"><?= $administrator->getName() ?></td>
                            <td class="text-left" width="40%"><?= $administrator->getEmail() ?></td>
                            <td class="text-right" width="15%"><?= $administrator->getPhone() ?></td>
                        </tr>
                    <?php endforeach ?>

                </tbody>
            </table>
        </div>
    </div>
</section>