<?php $this->layout('_template', $this->data) ?>

<?php if (isset($message)) : ?>
    <div id="message">
        <?php if ($message->getType() == 'success') : ?>
            <div class="alert alert-info"><?= "{$message->getText()}." ?></div>
        <?php else : ?>
            <div class="alert alert-danger"><?= "Ops, {$message->getText()}." ?></div>
        <?php endif ?>
    </div>
<?php endif ?>

<section id="section">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Cadastro de Administrador</h4>
            </div>
        </div>

        <div class="card-body">
            <form name="form_admin" method="POST" class="text-right">

                <div class="form-row align-items-center">
                    <label for="id" class="col-sm-2 col-form-label">Código</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="id" name="id" value="<?= $administrator->getId() ?>" readonly>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="name" class="col-sm-2 col-form-label">Nome</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="name" name="name" value="<?= $administrator->getName() ?>">
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-8">
                        <input type="email" class="form-control" id="email" name="email" value="<?= $administrator->getEmail() ?>">
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="password" class="col-sm-2 col-form-label">Senha</label>
                    <div class="col-sm-8">
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="phone" class="col-sm-2 col-form-label">Celular</label>
                    <div class="col-sm-8">
                        <input type="tel" class="form-control" id="phone" name="phone" value="<?= $administrator->getPhone() ?>">
                    </div>
                </div>

                <!---comeco modal-->
                <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">

                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Editar senha</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>

                            <div class="input-group mb-3 mt-3 container">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default">Senha</span>
                                </div>
                                <input type="text" class="form-control" aria-label="Exemplo do tamanho do input" aria-describedby="inputGroup-sizing-default">
                            </div>


                            <div class="input-group mb-3 mt-3 container">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default">Nova senha</span>
                                </div>
                                <input type="text" class="form-control" aria-label="Exemplo do tamanho do input" aria-describedby="inputGroup-sizing-default">
                            </div>


                            <div class="input-group mb-3 mt-3 container">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default">Confirmar senha</span>
                                </div>
                                <input type="text" class="form-control" aria-label="Exemplo do tamanho do input" aria-describedby="inputGroup-sizing-default">
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Salvar</button>
                                <button type="button" class="btn btn-primary">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>

                <!---fim modal-->
            </form>
        </div>
        <div class="card-footer">
            <div>
                <button name="save" type="button" class="btn btn-success">Salvar</button>
                <button name="clear" type="button" class="btn btn-warning">Limpar</button>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">Editar senha</button>
            </div>
        </div>
    </div>
</section>