<?php $this->layout('_template', $this->data) ?>

<section>
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Administrador</h4>
            </div>
        </div>

        <div class="card-body">
            <form name="form_admin" method="POST">
                <div class="form-row align-items-center text-right">
                    <label for="name" class="col-sm-2 col-form-label">Nome</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name">
                    </div>
                </div>
            </form>
        </div>

        <div class="card-footer">
            <div>
                <button name="buscar" type="button" onclick="document.form_busca_produtos.action='?class=ProdutosList&method=onReload'; document.form_busca_produtos.submit()" class="btn btn-success">Buscar</button>
                <button name="new" type="button" class="btn btn-secondary">Novo</button>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">

            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                        <th>
                        <th class="text-center" width="10%">Código</th>
                        <th class="text-left" width="40%">Nome</th>
                        <th class="text-left" width="40%">Email</th>
                        <th class="text-right" width="15%">Telefone</th>
                    </tr>
                </thead>
                <tbody>

                    <?php foreach ($administrators as $administrator) : ?>
                        <tr>
                            <td class="text-center">
                                <a href="#">
                                    <i class="fa fa-edit fa-lg blue" title="Editar"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="#">
                                    <i class="fa fa-trash fa-lg red" title="Excluir"></i>
                                </a>
                            </td>
                            <td class="text-center" width="10%"><?= $administrator->getId() ?></td>
                            <td class="text-left" width="40%"><?= $administrator->getName() ?></td>
                            <td class="text-left" width="40%"><?= $administrator->getEmail() ?></td>
                            <td class="text-right" width="15%"><?= $administrator->getPhone() ?></td>
                        </tr>
                    <?php endforeach ?>

                </tbody>
            </table>
        </div>
    </div>
</section>