<?php $this->layout('_template', $this->data) ?>

<section>
    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                <img src="/assets/images/TV_Aparecida_2010.png" width="30" height="30" class="rounded-circle ml-2">
                <a class="font-weight-light text-dark">TV Aparecida</a>
            </div>
            <div id="carouselExampleIndicators" class="carousel slide mt-3" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="/assets/images/full-screen-image-3.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/assets/images/full-screen-image-3.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/assets/images/full-screen-image-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="card-body">
                <h5 class="card-title">Evento natalino!!</h5>
                <p class="card-text">Fim de ano chegando, época de natal, época de alegria.</p>
                <p>
                    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                        Leia sobre
                    </a>
                </p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis distinctio ipsam nisi neque architecto vitae enim. Culpa magni eaque molestias quasi, placeat accusamus voluptates ipsam in harum ab rerum doloremque!
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                2 dias atrás
            </div>
        </div>
    </div>

    <div class="container">
        <div class="card text-center mt-3">
            <div class="card-header">
                <img src="/assets/images/TV_Aparecida_2010.png" width="30" height="30" class="rounded-circle ml-2">
                <a class="font-weight-light text-dark">TV Aparecida</a>
            </div>
            <div id="carouselExampleIndicators2" class="carousel slide mt-3" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators2" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators2" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators2" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="/assets/images/feed1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/assets/images/feed2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="/assets/images/full-screen-image-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators2" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators2" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <div class="card-body">
                <h5 class="card-title">Evento natalino!!</h5>
                <p class="card-text">Fim de ano chegando, época de natal, época de alegria.</p>
                <p>
                    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                        Leia sobre
                    </a>
                </p>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis distinctio ipsam nisi neque architecto vitae enim. Culpa magni eaque molestias quasi, placeat accusamus voluptates ipsam in harum ab rerum doloremque!
                    </div>
                </div>
            </div>
            <div class="card-footer text-muted">
                2 dias atrás
            </div>
        </div>
    </div>


</section>