<?php $this->layout('_template', $this->data) ?>

<section>
    <div class="card text-center">
        <div class="card-header">
            <img src="/assets/images/TV_Aparecida_2010.png" width="30" height="30" class="rounded-circle ml-2">
            <a class="font-weight-light text-dark">TV Aparecida</a>
        </div>
        <img class="card-img-top mt-3" src="/assets/images/full-screen-image-3.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Evento natalino!!</h5>
            <p class="card-text">Fim de ano chegando, época de natal, época de alegria.</p>
            <p>
                <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Leia sobre
                </a>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis distinctio ipsam nisi neque architecto vitae enim. Culpa magni eaque molestias quasi, placeat accusamus voluptates ipsam in harum ab rerum doloremque!
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            2 dias atrás
        </div>
    </div>

    <div class="card text-center mt-5">
        <div class="card-header">
            <img src="/assets/images/TV_Aparecida_2010.png" width="30" height="30" class="rounded-circle ml-2">
            <a class="font-weight-light text-dark">TV Aparecida</a>
        </div>
        <img class="card-img-top mt-3" src="/assets/images/full-screen-image-3.jpg" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">Evento natalino!!</h5>
            <p class="card-text">Fim de ano chegando, época de natal, época de alegria.</p>
            <p>
                <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                    Leia sobre
                </a>
            </p>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis distinctio ipsam nisi neque architecto vitae enim. Culpa magni eaque molestias quasi, placeat accusamus voluptates ipsam in harum ab rerum doloremque!
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            2 dias atrás
        </div>
    </div>


</section>