<?php $this->layout('_template', $this->data) ?>

<!--Começo Navbar-->
<nav class="navbar navbar-expand-lg navbar-light bgnav">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            <a class="navbar-brand" href="#">
                <img src="./assets/images/TV_Aparecida_2010.png" width="30" height="30"
                    class="d-inline-block align-top" alt="">
                Business Schedule
            </a>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Teste</a>
                    <a class="dropdown-item" href="#">Teste</a>
                    <a class="dropdown-item" href="#">Teste</a>
                </div>
            </li>

        </ul>
    </div>
</nav>
<!--Fim Navbar-->



<!--Começo Drag And Drop-->
<div class="boards container justify-content-center">
    <div class="board">
        <h3>Nome</h3>
        <div class="dropzone">
            <div class="card" draggable="true">
                <div class="status green"></div>
                <div class="content"> Igor Marcondes Santos</div>
            </div>
            <div class="card" draggable="true">
                <div class="status green"></div>
                <div class="content"> André de Moura Benedicto</div>
            </div>
        </div>

    </div>
    <div class="board">
        <h3>Estudio</h3>
        <div class="dropzone">
            <div class="card" draggable="true">
                <div class="status blue"></div>
                <div class="content"> Delta</div>
            </div>
            <div class="card" draggable="true">
                <div class="status blue"></div>
                <div class="content"> Bravo</div>
            </div>
        </div>
    </div>
    <div class="board">
        <h3>Programa</h3>
        <div class="dropzone">
            <div class="card" draggable="true">
                <div class="status red"></div>
                <div class="content"> Missa</div>
            </div>
            <div class="card" draggable="true">
                <div class="status red"></div>
                <div class="content"> Missa 2</div>
            </div>
        </div>
    </div>
    <div class="board">
        <h3>Horario</h3>
        <div class="dropzone">
            <div class="card" draggable="true">
                <div class="status red"></div>
                <div class="content"> 18:00</div>
            </div>
            <div class="card" draggable="true">
                <div class="status red"></div>
                <div class="content"> 18:00</div>
            </div>
        </div>
    </div>
</div>
<!--Fim Drag And Drop-->

<div class="row mt-5 justify-content-center">
    <button type="button" class="btn btn-primary mr-4">Apagar</button>
    <button type="button" class="btn btn-primary">Salvar</button>
</div>