<?php $this->layout('_template', $this->data) ?>


<div class="container-fluid">
    <h1>Escala</h1>

    <div class="row flex-nowrap">
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Funcionário</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Terça-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Quarta-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Quinta-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Sexta-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Sábado</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap" style="min-width: 200px;">Domingo</h4>
        </div>
    </div>

    <?php foreach ($employees as $employee) : ?>
        <div class="row flex-nowrap" data-row-id="<?= $employee->getId() ?>">
            <div class="col">
                <div grid-employees>

                    <div class="card bg-light border-dark mb-3" data-card-employee="<?= $employee->getId() ?>">
                        <div class="card-header"><?= $employee->getName() ?></div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title"><?= $employee->getJob() ?></h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                    
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div grid-days>
                    <div class="card bg-light border-dark mb-3" data-card-time="<?= $lastIdEmployeeHour++ ?>" style="max-width: 18rem;min-width: 200px;">
                        <div class="card-header">Cabeçalho 1</div>
                        <div class="card-body text-darrk">
                            <h5 class="card-title">Card Light</h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    <?php endforeach ?>
</div>

<div class="row mt-5 justify-content-center">
    <button type="button" class="btn btn-primary mr-4">Apagar</button>
    <button type="button" class="btn btn-primary">Salvar</button>
</div>