<?php $this->layout('_template', $this->data) ?>

<img class="wave" src="./">
	<div class="container">
		<div class="img">
			<img src="./assets/images/google.jpg">
		</div>
		<div class="login-content">
			<form action="index.html">
				<img src="./assets/images/google.jpg">
				<h2 class="title">Bem vindo!</h2>
           		<div class="input-div one">
           		   <div class="i">
           		   		<i class="fas fa-user"></i>
           		   </div>
           		   <div class="div">
           		   		<h5>Login</h5>
           		   		<input type="text" class="input">
           		   </div>
           		</div>
           		<div class="input-div pass">
           		   <div class="i"> 
           		    	<i class="fas fa-lock"></i>
           		   </div>
           		   <div class="div">
           		    	<h5>Senha</h5>
           		    	<input type="password" class="input">
            	   </div>
            	</div>
            	<a href="#">Esqueceu a senha?</a>
            	<input type="submit" class="btn" value="Entrar">
            </form>
        </div>
    </div>