<?php $this->layout('_template', $this->data) ?>

<?php $this->start('error') ?>
	<div class="alert alert-danger"><?= "Ops, {$error}." ?></div>
<?php $this->stop() ?>

<img class="wave" src="./assets/images/wave.png">
<div class="container">
	<div class="img">
		<img src="./assets/images/bs.png">
	</div>
	<div class="login-content">
		<form method="POST">
			<img src="./assets/images/TV_Aparecida_2010.png">
			<h2 class="title">Bem vindo!</h2>
			<div class="input-div one">
				<div class="i">
					<i class="fas fa-user"></i>
				</div>
				<div class="div">
					<h5>Login</h5>
					<input type="email" class="input" name="email" required>
				</div>
			</div>
			<div class="input-div pass">
				<div class="i"> 
					<i class="fas fa-lock"></i>
				</div>
				<div class="div">
					<h5>Senha</h5>
					<input type="password" class="input" name="password" required>
				</div>
			</div>
			<a href="#">Esqueceu a senha?</a>
			<button class="btn">Entrar</button>

			<?php if ($error) : ?>
				<?= $this->section('error') ?>
			<?php endif ?>
		</form>
	</div>
</div>