<?php $this->start('error') ?>
	<div class="alert alert-danger"><?= "Ops, {$error}." ?></div>
<?php $this->stop() ?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?></title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/light-bootstrap-dashboard.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="./assets/css/<?= $file ?>.css">
</head>
<body>

    <main>

		<img class="wave" src="./assets/images/wave.png">
		<div class="container">
			<div class="img">
				<img src="./assets/images/bs.png">
			</div>
			<div class="login-content">
				<form method="POST" autocomplete="off">
					<img src="./assets/images/TV_Aparecida_2010.png">
					<h2 class="title">Bem vindo!</h2>
					<div class="input-div one">
						<div class="i">
							<i class="fas fa-user"></i>
						</div>
						<div class="div">
							<h5>Login</h5>
							<input type="email" class="input" name="email" required>
						</div>
					</div>
					<div class="input-div pass">
						<div class="i"> 
							<i class="fas fa-lock"></i>
						</div>
						<div class="div">
							<h5>Senha</h5>
							<input type="password" class="input" name="password" required>
						</div>
					</div>
					<a href="#">Esqueceu a senha?</a>
					<button class="btn">Entrar</button>

					<?php if ($error) : ?>
						<?= $this->section('error') ?>
					<?php endif ?>
				</form>
			</div>
		</div>

	</main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"	integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"	crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="/assets/js/light-bootstrap-dashboard.js"></script>
    <script type="text/javascript" src="./assets/js/<?= $file ?>.js"></script>
    <script src="/assets/js/script.js"></script>

</body>
</html>