<?php $this->layout('_template', $this->data) ?>

<?php if (isset($message)) : ?>
    <div id="message">
        <?php if ($message->getType() == 'success') : ?>
            <div class="alert alert-info">
                <?= "{$message->getText()}." ?>
                <button type="button" aria-label="Close" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <?php else : ?>
            <div class="alert alert-danger">
                <?= "Ops, {$message->getText()}." ?>
                <button type="button" aria-label="Close" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>

<section id="section">
    <div class="card">
        <div class="card-header">
            <div class="card-title">
                <h4>Cadastro de Horário de Programa</h4>
            </div>
        </div>
        <div class="card-body">
            <form name="form_tvShowTime" method="POST" class="text-right">

                <div class="form-row align-items-center">
                    <label for="id" class="col-sm-2 col-form-label">Código</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="id" name="id" value="<?= $tvShowTime->getId() ?>" readonly>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="tvShow" class="col-sm-2 col-form-label mt-sm-2">Programa</label>
                    <div class="col-sm-3">
                        <select name="tvShow" id="tvShow" class="form-control" required>
                            <option>-- Selecione um Programa --</option>
                            <?php foreach ($tvShows as $tvShow) : ?>
                                <option value="<?= $tvShow->getId() ?>" <?= is_selected($tvShow->getId(), $tvShowTime->tvShow()->getId()) ?>>
                                    <?= $tvShow->getName() ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="startTime" class="col-sm-2 col-form-label mt-sm-2">Horário Inicial</label>
                    <div class="col-sm-2">
                        <input type="time" class="form-control" id="startTime" name="startTime" value="<?= date_formatt($tvShowTime->getStartTime(), 'H:i') ?>" required>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="finalTime" class="col-sm-2 col-form-label mt-sm-2">Horário Final</label>
                    <div class="col-sm-2">
                        <input type="time" class="form-control" id="finalTime" name="finalTime" value="<?= date_formatt($tvShowTime->getFinalTime(), 'H:i') ?>" required>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="date" class="col-sm-2 col-form-label mt-sm-2">Data</label>
                    <div class="col-sm-2">
                        <input type="date" class="form-control" id="date" name="date" value="<?= $tvShowTime->getDate() ?>" required>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="studio" class="col-sm-2 col-form-label mt-sm-2">Estúdio</label>
                    <div class="col-sm-3">
                        <select name="studio" id="studio" class="form-control" required>
                            <option>-- Selecione um Estúdio --</option>
                            <?php foreach ($studios as $studio) : ?>
                                <option value="<?= $studio->getId() ?>" <?= is_selected($studio->getId(), $tvShowTime->studio()->getId()) ?>>
                                    <?= $studio->getName() ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="switcher" class="col-sm-2 col-form-label mt-sm-2">Switcher</label>
                    <div class="col-sm-3">
                        <select name="switcher" id="switcher" class="form-control" required>
                            <option>-- Selecione um Switcher --</option>
                            <?php foreach ($switchers as $switcher) : ?>
                                <option value="<?= $switcher->getId() ?>" <?= is_selected($switcher->getId(), $tvShowTime->switcher()->getId()) ?>>
                                    <?= $switcher->getName() ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>

                <div class="form-row align-items-center">
                    <label for="mode" class="col-sm-2 col-form-label mt-sm-2">Formato</label>
                    <div class="col-sm-2">
                        <select name="mode" id="mode" class="form-control">
                            <option value="1" <?= is_selected('Ao Vivo', $tvShowTime->getMode()) ?>>Ao Vivo</option>
                            <option value="1" <?= is_selected('Gravado', $tvShowTime->getMode()) ?>>Gravado</option>
                            <option value="3" <?= is_selected('Unidade Móvel', $tvShowTime->getMode()) ?>>Unidade Móvel</option>
                        </select>
                    </div>
                </div>

            </form>
        </div>
        <div class="card-footer">
            <div>
                <button name="save" type="button" class="btn btn-success">Salvar</button>
                <button name="clear" type="button" class="btn btn-warning">Limpar</button>
                <button name="back" type="button" class="btn btn-info" onclick="location.href = '/horario-programa'">Voltar</button>
            </div>
        </div>
    </div>
</section>