<?php $this->layout('_template', ['title' => '']) ?>

<style>
    .grid-square {
        width: 100px;
        height: 100px;
        display: inline-block;
        background-color: #fff;
        border: solid 1px rgb(0,0,0,0.2);
        padding: 10px;
        margin: 12px;
    }

    .highlighted {
        background-color: #9AB6F1;
    }

    .blue-background-class {
        background-color: #C8EBFB;
    }

    .highlight {
        background-color: #B7F8C7;
    }
</style>

<div id="grid" class="row">
    <h4 class="col-12">Grid Example</h4>
    <div id="gridDemo" class="col">
        <div class="grid-square">Item 1</div>
        <div class="grid-square">Item 2</div>
        <div class="grid-square">Item 3</div>
        <div class="grid-square">Item 4</div>
        <div class="grid-square">Item 5</div>
        <div class="grid-square">Item 6</div>
        <div class="grid-square">Item 7</div>
        <div class="grid-square">Item 8</div>
        <div class="grid-square">Item 9</div>
        <div class="grid-square">Item 10</div>
        <div class="grid-square">Item 11</div>
        <div class="grid-square">Item 12</div>
        <div class="grid-square">Item 13</div>
        <div class="grid-square">Item 14</div>
        <div class="grid-square">Item 15</div>
        <div class="grid-square">Item 16</div>
        <div class="grid-square">Item 17</div>
        <div class="grid-square">Item 18</div>
        <div class="grid-square">Item 19</div>
        <div class="grid-square">Item 20</div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<script>
    const gridDemo = document.getElementById('gridDemo')

    new Sortable(gridDemo, {
        swap: true,
        swapClass: "highlighted",
        animation: 150,
        ghostClass: 'blue-background-class'
    })

    // Sortable.create(gridDemo, {
    //     swap: true,
    //     swapClass: "highlighted"
    // });
</script>