<html lang="pt-br"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Business Schedule - Escala</title>
    <link rel="shortcut icon" href="/assets/images/TV_Aparecida_2010.png" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&amp;display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/animate.min.css">
    <link rel="stylesheet" href="/assets/css/light-bootstrap-dashboard.css">
    <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/css/style.css">
    <!-- <script src="https://kit.fontawesome.com/a81368914c.js"></script> -->
    <link rel="stylesheet" type="text/css" href="/assets/css/schedule.css">
<style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style></head>
<body class="" style="">

    <div class="wrapper">
        <side class="sidebar" data-color="blue" data-image="/assets/images/sidebar-4.jpg" id="navigation-example-2">
            <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="/" class="simple-text">
                        Business Schedule
                    </a>
                </div>
                <ul class="nav nav-mobile-menu">
                        <ul class="nav navbar-nav">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-dashboard"></i>
                                    <p class="d-inline-block d-lg-none d-md-none ml-0">Dashboard</p>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Ação</a>
                                    <a class="dropdown-item" href="#">Outra ação</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Algo mais aqui</a>
                                </div>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav ml-lg-auto align-items-lg-center">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <p class="d-inline-block">
                                        Atalhos
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/escala">Escalas</a></li>
                                    <li><a href="/funcionario">Funcionários</a></li>
                                    <li><a href="/programa">Programas</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="/sair" class="my-0">
                                    <p>Sair</p>
                                </a>
                            </li>
                            <li class="separator d-lg-none d-md-none"></li>
                        </ul>
                    </ul><ul class="nav flex-column">
                    <li class="nav-item"><a class="nav-link" href="/escala"><i class="fa fa-calendar" aria-hidden="true"></i> Cadastrar Escala</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i class="fa fa-industry fa-sm" aria-hidden="true"></i> Editar Escala</a></li>
                    <li class="nav-item"><a class="nav-link" href="/funcionario"><i class="fa fa-users" aria-hidden="true"></i> Funcionários</a></li>
                    <li class="nav-item"><a class="nav-link" href="/estudio"><i class="fa fa-video-camera" aria-hidden="true"></i> Estúdios</a></li>
                    <li class="nav-item"><a class="nav-link" href="/switcher"><i class="fa fa-microphone" aria-hidden="true"></i> Switchers</a></li>
                    <li class="nav-item"><a class="nav-link" href="/programa"><i class="fa fa-television" aria-hidden="true"></i> Programas</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin"><i class="fa fa-user" aria-hidden="true"></i> Administradores</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i class="fa fa-file-text-o" aria-hidden="true"></i> Solicitar Troca de Horário</a></li>
                </ul>
            </div>
        <div class="sidebar-background" style="background-image: url(/assets/images/sidebar-4.jpg) "></div></side>
        <div class="main-panel">
            <nav class="navbar navbar-default navbar-light navbar-expand-lg navbar-fixed">
                <header class="container-fluid flex-nowrap">
                    <div class="navbar-header mx-0">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation-example-2" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <a class="navbar-brand py-0" href="#"> <i class="fa fa-code"></i> Código-fonte</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-dashboard"></i>
                                    <p class="d-inline-block d-lg-none d-md-none ml-0">Dashboard</p>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="#">Ação</a>
                                    <a class="dropdown-item" href="#">Outra ação</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Algo mais aqui</a>
                                </div>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav ml-lg-auto align-items-lg-center">
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle my-0" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <p class="d-inline-block">
                                        Atalhos
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/escala">Escalas</a></li>
                                    <li><a href="/funcionario">Funcionários</a></li>
                                    <li><a href="/programa">Programas</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="/sair" class="my-0">
                                    <p>Sair</p>
                                </a>
                            </li>
                            <li class="separator d-lg-none d-md-none"></li>
                        </ul>
                    </div>
                </header>
            </nav>
            <main class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">

                            

<div class="container-fluid">
    <h1>Escala</h1>
    <div class="row flex-nowrap">
        <div class="col">
            <h4 class="text-nowrap">Funcionário</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
        <div class="col">
            <h4 class="text-nowrap">Segunda-Feira</h4>
        </div>
    </div>

    <div class="row flex-nowrap">
        <div class="col">

            <div card-employees>
                <div class="card bg-light border-dark mb-3" data-card-employee="2" style="">
                    <div class="card-header">Fulano de Tal</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Cinegrafista</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col">
        
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="8" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row flex-nowrap">
        <div class="col">
            <div card-employees>
                <div class="card bg-light border-dark mb-3" data-card-employee="1" draggable="false" style="">
                    <div class="card-header">André Moura</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Programador</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row flex-nowrap">
        <div class="col">
            <div card-employees>
                <div class="card bg-light border-dark mb-3" data-card-employee="1" draggable="false" style="">
                    <div class="card-header">André Moura</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Programador</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row flex-nowrap">
        <div class="col">
            <div card-employees>
                <div class="card bg-light border-dark mb-3" data-card-employee="1" draggable="false" style="">
                    <div class="card-header">André Moura</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Programador</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row flex-nowrap">
        <div class="col">
            <div card-employees>
                <div class="card bg-light border-dark mb-3" data-card-employee="1" draggable="false" style="">
                    <div class="card-header">André Moura</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Programador</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col">
            <div card-days>
                <div class="card bg-light border-dark mb-3" data-card-time="1" style="max-width: 18rem; min-width: 200px;" draggable="false">
                    <div class="card-header">Cabeçalho 1</div>
                    <div class="card-body text-darrk">
                        <h5 class="card-title">Card Light</h5>
                        <p class="card-text"></p>
                    </div>
                </div>
            </div>
        </div>

    </div>

              
</div>

<div class="row mt-5 justify-content-center">
    <button type="button" class="btn btn-primary mr-4">Apagar</button>
    <button type="button" class="btn btn-primary">Salvar</button>
</div>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        <a target="newwindow" href="https://github.com/andr3m0ur4/Business-Schedule"> PI - Programando com Orientação a Objetos </a>
                    </p>
                </div>
            </footer>
        </div>
    </div>

    <div id="myModal"><div><button type="button" class="btn btn-primary d-none" id="btnModal" data-toggle="modal" data-target="#modalEmployeeTime"></button>

<!-- Modal -->
<div class="modal fade" id="modalEmployeeTime" tabindex="-1" role="dialog" data-id="" aria-labelledby="TituloModalCentralizado" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title TituloModalCentralizado" id="time-name"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th scope="row"><i class="fa fa-bars"></i> Função</th>
                                <td id="time-job"></td>
                            </tr>
                            <tr>
                                <th scope="row"><i class="fa fa-info-circle"></i> Status</th>
                                <td><span class="badge badge-danger">Nome</span></td>
                            </tr>
                            <tr>
                                <th scope="row"><i class="fa fa-clock-o"></i> Horário inicial</th>
                                <td colspan="2" id="time-start-time">
                                    <input type="time" id="startTime">
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><i class="fa fa-clock-o"></i> Horário final</th>
                                <td colspan="2" id="final-time">
                                    <input type="time" name="" id="finalTime">
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><i class="fa fa-calendar-plus-o"></i> Data</th>
                                <td colspan="2" id="time-date">
                                    <input type="date" name="" id="date">
                                </td>
                            </tr>
                            <tr>
                                <td scope="row"><i class="fa fa-tv"></i> Programas</td>
                                <td>
                                    <select class="mdb-select md-form" multiple="" searchable="Search here..">
                                        <option value="" data-fas="laptop blue-text"> example 1</option>
                                        <option value="" data-far="circle red-text">
                                            example
                                            2</option>
                                        <option value="" data-fab="facebook brown-text">
                                            example
                                            3</option>
                                    </select>
                                    <button class="btn-save btn btn-primary btn-sm">Save</button>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><i class="fa fa-plus"></i> Adicionar</th>
                            </tr>
                        </tbody>
                    </table>

                    <hr>
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <td scope="row"><i class="fa fa-id-badge"></i> <b>André Moura</b>
                                    <p>Um comentario</p>
                                </td>
                                <td>Hoje as 11:30</td>
                            </tr>
                            <tr>
                                <td scope="row"><i class="fa fa-id-badge"></i> <b>André Moura</b>
                                    <p>Um comentario</p>
                                </td>
                                <td>Hoje as 11:32</td>
                            </tr>
                            <tr>
                                <td scope="row"><i class="fa fa-plus"></i> Adicionar um comentário...
                                    <div class="form-group">
                                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                    </div>
                                </td>
                                <td>
                                    <i class="fa fa-paperclip"></i>
                                    <i class="fa fa-at"></i>
                                    <i class="fa fa-arrow-circle-up"></i>
                                </td>
                            </tr>
                    </tbody></table>
                    <hr>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="saveTime">Salvar horário</button>
            </div>

            <script>
                $(document).ready(function () {
                    $('.mdb-select').materialSelect();
                });
            </script>

        </div>
    </div>
</div>
<!--   Final do conteudo da pagina --></div><div><button type="button" class="btn btn-primary d-none" id="btnModalEmployee" data-toggle="modal" data-target="#modalEmployee"></button>

<!-- Modal -->
<div class="modal fade" id="modalEmployee" tabindex="-1" role="dialog" aria-labelledby="TituloModalCentralizado" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title TituloModalCentralizado" id="employee-name">André Moura</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th scope="row">
                                    <i class="fa fa-bars"></i> Função
                                </th>
                                <td id="employee-job">Programador</td>
                            </tr>
                            <tr>
                                <th scope="row">
                                    <i class="fa fa-bars"></i> E-mail
                                </th>
                                <td id="employee-email">andre@teste.com</td>
                            </tr>
                            <tr>
                                <th scope="row">
                                    <i class="fa fa-bars"></i> Telefone
                                </th>
                                <td id="employee-phone">12988563036</td>
                            </tr>
                            <tr>
                                <th scope="row">
                                    <i class="fa fa-bars"></i> Descrição
                                </th>
                                <td>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime in, natus, reiciendis explicabo temporibus sint nulla dolorem fuga nam nesciunt at omnis voluptatum non. Illo cumque aspernatur expedita adipisci minus!</td>
                            </tr>
                        </tbody>
                    </table>

                    <hr>
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <td scope="row"><i class="fa fa-plus"></i> Envie uma mensagem...
                                    <div class="form-group">
                                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                    </div>
                                </td>
                                <td><i class="fa fa-paperclip"></i> <i class="fa fa-at"></i> <i class="fa fa-arrow-circle-up"></i></td>
                            </tr>
                        </tbody>
                    </table>
                    <hr>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Salvar mudanças</button>
            </div>
        </div>
    </div>
</div>
<!--   Final do conteudo da pagina --></div><div><button type="button" class="btn btn-primary d-none" id="btnModalSchedule" data-toggle="modal" data-target="#modalSchedule"></button>

<!---comeco modal-->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar programa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="alert alert-warning question d-none" id="question">
                Deseja realmente excluir o registro?
                <a href="#" class="btn btn-light float-right">Sim</a>
            </div>

            <div class="alert alert-info">
                Registro excluído com sucesso
            </div>

            <section>
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <h4>Programas</h4>
                        </div>
                    </div>

                    <div class="card-body">
                        <form name="form_tvShow" method="get">
                            <div class="form-row align-items-center text-right">
                                <label for="name" class="col-sm-2 col-form-label">Nome</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="name" name="name">
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="card-footer">
                        <div>
                            <button name="search" type="button" class="btn btn-success">Buscar</button>
                            <button name="new" type="button" class="btn btn-secondary">Novo</button>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">

                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                    </th><th>
                                    </th><th class="text-center" width="10%">Código</th>
                                    <th class="text-left" width="80%">Nome</th>

                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td class="text-center">
                                        <a href="#">
                                            <i class="fa fa-edit fa-lg blue" title="Editar"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <a href="#">
                                            <i class="fa fa-trash fa-lg red" title="Excluir"></i>
                                        </a>
                                    </td>
                                    <td class="text-center" width="10%">1</td>
                                    <td class="text-left" width="30%">
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </section>

            <div class="modal-footer">
                <button id="changePassword" name="changePassword" type="button" class="btn btn-secondary">Salvar</button>
                <button type="button" class="btn btn-primary">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!---fim modal--></div></div>

    <script src="/assets/js/Chart.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="/assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>
    <!-- jsDelivr :: Sortable :: Latest (https://www.jsdelivr.com/package/npm/sortablejs) -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <script src="/assets/js/localStorage.js"></script>
    <script type="text/javascript" src="/assets/js/schedule.js"></script>
    <script src="/assets/js/script.js"></script>


</body></html>